# Generated by Django 4.0 on 2022-06-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('skill', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=200)),
                ('langue', models.CharField(max_length=500)),
                ('interest', models.CharField(max_length=1000)),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('project', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
