# Generated by Django 4.0 on 2022-06-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
