# Generated by Django 4.0 on 2022-06-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='Id',
        ),
    ]
