# Generated by Django 4.0 on 2022-06-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_rename_id_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Id',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
