# Generated by Django 4.0 on 2022-06-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
