# Generated by Django 4.0 on 2022-06-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desription',
            new_name='description',
        ),
    ]
